services:
  beszel:
    container_name: beszel
    image: ghcr.io/henrygd/beszel/beszel@sha256:99181067e5a46b3147231f456114280a8119eed371808bce79e6e7f173946975
    restart: unless-stopped
    environment:
      TZ: Europe/Prague
    volumes:
      - /service/docker/data/beszel:/beszel_data
    networks:
      - main_default

  beszel-agent:
    container_name: beszel-agent
    image: ghcr.io/henrygd/beszel/beszel-agent@sha256:6c8c99e3de2ab82f503f0ff8f0c3a1dbd4cf0e735cf2c24175fa2db826994a60
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: "45876"
      KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINfn1BjDW8THgCGVSeWasZ1lK8NC36RmDpJ1CN3AA9dx

networks:
  main_default:
    external: true
