services:
  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow 
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
    volumes:
      - langflow-data:/app/langflow
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omada.rule=Host(`langflow.mlocal.eu`)"
      - "traefik.http.routers.omada.entrypoints=websecure"
    networks:
      - main_default

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    expose:
      - 5432
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
    networks:
      - main_default

volumes:
  langflow-postgres:
  langflow-data:

networks:
  main_default:
    name: main_default
    external: true
