services:
  mysql_chat:
    container_name: mysql_chat
    build:
      context: ./mysql_chat
    ports:
      - "84:5001"      
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mysqlchat.rule=Host(`mysqlchat.mlocal.eu`)"
      - "traefik.http.routers.mysqlchat.entrypoints=websecure"
      - "traefik.http.services.mysqlchat.loadbalancer.server.port=84"
    networks:
      - main_default

networks:
  main_default:
    name: main_default
    external: true
