services:
  netdata:
    container_name: netdata
    image: netdata/netdata@sha256:6ae048e5d400c40208802960f5f7e9d1fc8b489bd6c9b8311acde6102260d643
    hostname: degas
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      TZ: Europe/Prague
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - main_default

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

networks:
  main_default:
    external: true
